const sidebarStyles = {
  sidebar: {
    height: '100',
    width: '70px',
    backgroundColor: '#202225',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '20px 0',
  },
  iconContainer: {
    marginBottom: '15px',
    width: '70px',
    height: '50px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#202225',
    borderLeft: '3px solid transparent',
    transition: 'border-left 0.2s ease, border-radius 0.2s ease',
  },
  iconContainerHover: {
    marginBottom: '15px',
    width: '70px',
    height: '50px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#202225',
    borderLeft: '3px solid white',
    transition: 'border-left 0.2s ease, border-radius 0.2s ease',
  },
  iconContainerActive: {
    marginBottom: '15px',
    width: '70px',
    height: '50px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    transition: 'border-left 0.2s ease, border-radius 0.2s ease',
    borderLeft: '3px solid #5865F2',
    backgroundColor: '#2F3136',
  },
  serverIcon: {
    width: '50px',
    height: '50px',
    borderRadius: '50%',
    transition: 'border-radius 0.2s ease',
  },
  serverIconHover: {
    width: '50px',
    height: '50px',
    borderRadius: '30%',
    transition: 'border-radius 0.2s ease',
  },
  icon: {
    fontSize: '24px',
    color: 'white',
  },
  popup: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popupContent: {
    backgroundColor: '#202225',
    padding: '20px',
    borderRadius: '10px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    width: '300px',
  },
  input: {
    width: '90%',
    padding: '10px',
    marginBottom: '10px',
    borderRadius: '5px',
    border: '1px solid #ccc',
  },
  buttonContainer: {
    display: 'flex',
    justifyContent: 'space-between',
  },
  submitButton: {
    padding: '10px 15px',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  closeButton: {
    padding: '10px 15px',
    backgroundColor: '#dc3545',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
  },
};

export default sidebarStyles;